/*
    Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGSAP } from "@gsap/react";
import { Float } from "@react-three/drei";
import type { GroupProps } from "@react-three/fiber";
import gsap from "gsap";
import { useRef, useState } from "react";
import type * as THREE from "three";

export const Cube = (props: GroupProps) => {
  const cubeRef = useRef<THREE.Mesh>(null);
  const [hovered, setHovered] = useState(false);

  useGSAP(() => {
    if (!cubeRef.current) return;

    gsap
      .timeline({
        repeat: -1,
        repeatDelay: 0.5,
      })
      .to(cubeRef.current.rotation, {
        y: hovered ? "+=2" : `+=${Math.PI * 2}`,
        x: hovered ? "+=2" : `-=${Math.PI * 2}`,
        duration: 2.5,
        stagger: {
          each: 0.15,
        },
      });
  });

  return (
    <Float floatIntensity={2}>
      <group
        position={[9, -4, 0]}
        rotation={[2.6, 0.8, -1.8]}
        scale={0.74}
        dispose={null}
        {...props}
      >
        <mesh
          ref={cubeRef}
          castShadow
          receiveShadow
          onPointerEnter={() => setHovered(true)}
        >
          <boxGeometry args={[2, 2, 2]} />
          <meshStandardMaterial
            color="#fb7185"
            emissive="#7f1d1d"
            emissiveIntensity={0.2}
            metalness={0.18}
            roughness={0.34}
          />
        </mesh>
      </group>
    </Float>
  );
};
