/*
    Auto-generated by: https://github.com/pmndrs/gltfjsx
    Command: npx gltfjsx@6.5.0 react.glb -T
    Author: xenadus (https://sketchfab.com/xenadus)
    License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
    Source: https://sketchfab.com/3d-models/react-logo-76174ceeba96487f9863f974636f641e
*/

import { Float, useGLTF } from "@react-three/drei";
import { useFrame, type GroupProps } from "@react-three/fiber";
import { useRef } from "react";
import * as THREE from "three";
import type { GLTF } from "three-stdlib";

import { referenceAsset } from "../constants/assets";

const REACT_MODEL = referenceAsset("models/react.glb");

type GLTFResult = GLTF & {
  nodes: {
    ["React-Logo_Material002_0"]: THREE.Mesh;
  };
  materials: {
    ["Material.002"]: THREE.MeshStandardMaterial;
  };
};

export const ReactLogo = (props: GroupProps) => {
  const { nodes, materials } = useGLTF(REACT_MODEL) as GLTFResult;
  const groupRef = useRef<THREE.Group>(null);
  const smoothedScroll = useRef(0);

  useFrame(({ clock }, delta) => {
    if (!groupRef.current) return;
    const targetScroll = typeof window === "undefined" ? 0 : window.scrollY;
    smoothedScroll.current = THREE.MathUtils.damp(
      smoothedScroll.current,
      targetScroll,
      2,
      delta
    );
    const scroll = smoothedScroll.current;
    groupRef.current.rotation.x = clock.elapsedTime * 0.3 + scroll * 0.0002;
    groupRef.current.rotation.y = clock.elapsedTime * 0.5 + scroll * 0.0004;
    groupRef.current.rotation.z = clock.elapsedTime * 0.2 + scroll * 0.00015;
  });

  return (
    <Float floatIntensity={1}>
      <group
        ref={groupRef}
        position={[8, 8, 0]}
        scale={0.4}
        {...props}
        dispose={null}
      >
        <mesh
          geometry={nodes["React-Logo_Material002_0"].geometry}
          material={materials["Material.002"]}
          position={[0, 0.079, 0.181]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.392, 0.392, 0.527]}
        />
      </group>
    </Float>
  );
};

useGLTF.preload(REACT_MODEL);
